codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/README.md.gotmpl
codefresh/files/indexes/2.6/agenttasks.json
codefresh/files/indexes/2.6/workflowprocesses.json
codefresh/values.yaml
scripts/update_re_images.sh

onprem: 2.6.1

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/README.md.gotmpl

onprem: 2.6.3

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/tests/misc/misc_test.yaml
codefresh/values.yaml

onprem: 2.6.9

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/files/assets/accounts-dev.json
codefresh/files/assets/packs.json
codefresh/files/mongoSeedJobScript.sh
codefresh/templates/_helpers.tpl
codefresh/templates/configmaps/runtimeEnvironments.json.tpl
codefresh/templates/gencerts/job-gencerts.yaml
codefresh/templates/hooks/set-mongodb-compat-version.yaml
codefresh/templates/hooks/update-system-re.yaml
codefresh/templates/ingress.yaml
codefresh/templates/internal-gateway.yaml
codefresh/templates/seed/mongo-seed-config.yaml
codefresh/templates/seed/mongo-seed-job.yaml
codefresh/templates/seed/postgres-seed-job.yaml
codefresh/tests/misc/global_constrains_test.yaml
codefresh/values.yaml

onprem: 2.7.1

---

codefresh/.ci/values/external-secrets.yaml
codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/files/mongoSeedJobScript.sh
codefresh/values.yaml

onprem: 2.7.2

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem: 2.6.10

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem: 2.7.5

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem: 2.6.11

---

codefresh/Chart.yaml
codefresh/README.md
codefresh/templates/ingress.yaml
codefresh/tests/ingress/ingress_test.yaml
codefresh/values.yaml

onprem: 2.7.8

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

Onprem 2.7.9

---

codefresh/.ci/values/mtls-mongodb-redis.yaml
codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md

onprem: 2.6.13

---

codefresh/README.md

fix: README.md

---

codefresh/README.md
codefresh/README.md.gotmpl

fix: indxes docs

---

codefresh/README.md
codefresh/README.md.gotmpl

Add indexes docs for 2.8

---

codefresh/README.md
codefresh/README.md.gotmpl
indexes/codefresh/agenttasks.json
indexes/codefresh/feature-store-versioned.json
indexes/codefresh/users.json
indexes/codefresh/workflowprocesses.json
indexes/read-models/analysisruns.json
indexes/read-models/images-binaries.json
indexes/read-models/product-releases.json
indexes/read-models/releases.json
indexes/read-models/rollouts.json

It depends on:
- https://github.com/codefresh-io/codefresh-onprem-helm/pull/65
- https://github.com/codefresh-io/codefresh-onprem-helm/pull/66

fix: 2.8 docs mongo

---

codefresh/Chart.yaml
codefresh/README.md
codefresh/README.md.gotmpl

onprem: 2.8.0

---

codefresh/Chart.yaml
codefresh/README.md
codefresh/README.md.gotmpl
codefresh/files/postgresSeedJobScript.sh

onprem: 2.8.1

---

codefresh/Chart.yaml
codefresh/README.md
codefresh/files/postgresSeedJobScript.sh

onprem: 2.8.2

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem 2.8.4

---

indexes/codefresh/workflowprocesses.json

This removes TTL for `codefresh.workflowprocesses` as it's up to the customer to configure retention policy.

docs(indexes): remove redundant TTL

---

codefresh/.ci/values/defaults.yaml
codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem: 2.8.13

---

README.md
README.md.gotmpl
indexes/codefresh/agenttasks.json
indexes/codefresh/feature-store-versioned.json
indexes/codefresh/users.json
indexes/codefresh/workflowprocesses.json
indexes/read-models/accounts.json
indexes/read-models/analysisruns.json
indexes/read-models/images-binaries.json
indexes/read-models/product-components.json
indexes/read-models/product-releases.json
indexes/read-models/promotions.json
indexes/read-models/releases.json
indexes/read-models/rollouts.json

This documents indexes and DBs compatibility for 2.9.
https://codefresh-io.atlassian.net/browse/CR-31145

docs(2.9): document indexes and DBs compatibility

---

charts/codefresh/values.yaml

chore(CR-29499): bump kubectl, mongosh, postgres

---

README.md
README.md.gotmpl
charts/codefresh/values.yaml

docs: added ability to disable postgres store for eventbus and set schema name for audit
