codefresh-io/codefresh-onprem-helm

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/README.md.gotmpl
codefresh/values.yaml

onprem: 2.6.2

---

codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem: 2.6.4

---

codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

Patch - 2.6.5 update open source components

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem: 2.6.6

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem: 2.6.7 security updates

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem: 2.6.8

---

codefresh/.ci/values/external-secrets.yaml
codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/README.md.gotmpl
codefresh/files/indexes/2.6/agenttasks.json
codefresh/files/indexes/2.6/analysisruns.json
codefresh/files/indexes/2.6/images-binaries.json
codefresh/files/indexes/2.6/releases.json
codefresh/files/indexes/2.6/rollouts.json
codefresh/files/indexes/2.6/workflowprocesses.json
codefresh/templates/secrets/regsecret.yaml
codefresh/tests/misc/global_constrains_test.yaml
codefresh/tests/misc/misc_test.yaml
codefresh/tests/values/global.yaml
codefresh/values.yaml
scripts/update_re_images.sh

onprem: 2.7.0

---

codefresh/.ci/values/external-secrets.yaml
codefresh/.ci/values/mtls-mongodb-redis.yaml
codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem: 2.7.6

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem: 2.7.7

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md

onprem: 2.6.12

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/templates/hooks/delete-consul-svc/delete-consul-svc-job.yaml
codefresh/templates/hooks/delete-consul-svc/delete-consul-svc-rbac.yaml
codefresh/values.yaml

https://codefresh-io.atlassian.net/browse/CR-28817
https://codefresh-io.atlassian.net/browse/CR-29015
! `./codefresh/.ci/runtime-images.sh` script failed with error `Error: connect ECONNREFUSED 127.0.0.1:80`

onprem: 2.7.12

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/README.md.gotmpl

onprem: 2.7.13

---

codefresh/README.md

fix: links and indexes

---

codefresh/Chart.yaml
codefresh/README.md
codefresh/templates/hooks/delete-consul-svc/delete-consul-svc-job.yaml

onprem: 2.7.14

---

indexes/read-models/product-releases.json

Added product-releases indexes

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md

onprem 2.8.5

---

codefresh/README.md
codefresh/README.md.gotmpl

fix(doc): elasticache cluster mode note

---

codefresh/.ci/values/defaults.yaml
codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml

onprem-2.7.17

---

codefresh/Chart.lock
codefresh/Chart.yaml
codefresh/README.md
codefresh/values.yaml
scripts/update_re_images.sh

onprem-2-9-10

---

README.md
charts/codefresh/templates/hooks/pre-upgrade/enable-stable-flags-rabbitmq-job.yaml
charts/codefresh/tests/misc/global_constrains_test.yaml
charts/codefresh/values.yaml

feat: build latest 0.0.0 dev chart

---

README.md
charts/codefresh/Chart.yaml
charts/codefresh/values.yaml

added: ability to disable postgres store for eventbus and set schema name for audit

---

README.md
README.md.gotmpl
indexes/codefresh/agenttasks.json
indexes/codefresh/feature-store-versioned.json
indexes/codefresh/users.json
indexes/codefresh/workflowprocesses.json
indexes/read-models/accounts.json
indexes/read-models/analysisruns.json
indexes/read-models/images-binaries.json
indexes/read-models/product-components.json
indexes/read-models/product-releases.json
indexes/read-models/promotions.json
indexes/read-models/releases.json
indexes/read-models/rollouts.json

docs: document 2.9 indexes and changes in schema

---

charts/codefresh/Chart.yaml
charts/codefresh/values.yaml

feat: added ability to disable postgres store for eventbus and set schema name for audit

---

charts/codefresh/Chart.yaml

fix: feature flags

---

charts/codefresh/Chart.yaml

chore: fix security vulnerabilities
